language: java

branches:
  only:
  - master

stages:
- name: All

jobs:
  include:
  - stage: All
    script:
    - mvn verify

before_install:
- openssl aes-256-cbc -K $encrypted_27a7b75a5f77_key -iv $encrypted_27a7b75a5f77_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    all_branches: master

notifications:
  email: false
