language: java

branches:
  only:
  - master

stages:
- name: "Verification"

jobs:
  include:
  - stage: "Verification"
    script:
    - mvn clean install && mvn verify

notifications:
  email: false
