language: java

branches:
  only:
  - master

stages:
- name: "All"

jobs:
  include:
  - stage: "All"
    script:
    - mvn verify

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
