language: java

branches:
  only:
  - master

stages:
- name: All

jobs:
  include:
  - stage: All
    script:
    - mvn verify

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script:
  - openssl aes-256-cbc -K $encrypted_27a7b75a5f77_key -iv $encrypted_27a7b75a5f77_iv
    -in .travis/id_rsa.enc -out .travis/id_rsa -d
  - ls .travis
  - bash scripts/deploy.sh
  on:
    branch: master

notifications:
  email: false
